-- Supabase SQL Editor'da bir kez calistir (wheel paneli icin)
create table if not exists wheel_trades (
  id bigint generated by default as identity primary key,
  opened_at timestamptz default now(),
  sym text not null,
  kind text not null default 'CSP',          -- CSP | CC
  expiry date,
  strike numeric,
  qty int default -1,
  fill numeric,                              -- satis fiyati ($/hisse)
  premium numeric,                           -- fill x 100
  collateral numeric,
  status text default 'open',                -- open | closed
  close_price numeric,
  close_reason text,                         -- expired | closed_75 | assigned | manual
  closed_at timestamptz,
  pnl numeric,
  note text
);

create table if not exists iv_history (
  ts timestamptz default now(),
  sym text not null,
  spot numeric,
  atm_iv numeric,
  rv20 numeric
);
